language: python
python:
  - "2.7"
#before_install:
#
# command to install dependencies
#install: "pip install -r requirements.txt --use-mirrors"
install: "pip install"
# This is needed, otherwise, nosetests will import try to import wx.
#before_script:
    #- rm abipy/gui/__init__.py 
    #- export LD_LIBRARY_PATH=/usr/lib/:$LD_LIBRARY_PATH
    #- python -m netCDF4_utils
    #- abipy/dev_scripts/check_netcdf4.py
# command to run tests
script: nosetests
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
