language: python
cache: pip

#dist: precise
sudo: false

env:
  global:
    - ABINIT_VERSION=8.8.2
    - ABIPY_PYTEST=yes
    - OPENBLAS_NUM_THREADS=1
    - OMP_NUM_THREADS=1

matrix:
  include:
    - os: linux
      python: 2.7
      env: 
        - ABINIT_VERSION=8.6.1 ABIPY_INSTALLER=conda
    - os: linux
      python: 3.6
      env: 
        - ABINIT_VERSION=8.6.1 ABIPY_INSTALLER=pip ABIPY_COVERALLS=yes
#    - os: linux
#      python: 3.7
#      # https://github.com/travis-ci/travis-ci/issues/9815
#      dist: xenial
#      sudo: true
#      env: 
#        - ABIPY_INSTALLER=pip

install:
  #- set -ev  # exit on first error, print each command
  - env
  - ulimit -s unlimited

  - |
      if [ "${ABIPY_INSTALLER}" == "pip" ]; then
        # pip-based installation.
        source dev_scripts/conda_get.sh  # Needed for Abinit

        travis_wait pip install -r requirements.txt
        travis_wait pip install -r requirements-optional.txt
  
      elif [ "${ABIPY_INSTALLER}" == "conda" ]; then
        # Install conda https://conda.io/docs/travis.html
        source dev_scripts/conda_get.sh
        source dev_scripts/conda_install.sh
        #- conda uninstall -y pymatgen
        #- conda uninstall -y abipy
      fi

  # Install abinit from abinit conda channel.
  - echo "Installing abinit from abinit channel ..."
  - conda config --add channels conda-forge
  - conda install -y -c abinit abinit=${ABINIT_VERSION}
  - abinit --version
  - abinit --build

  # Get pymatgen from matsci
  #- conda config --add channels matsci
  # Use my pymatgen fork
  #- git clone https://github.com/gmatteo/pymatgen.git && cd pymatgen && pip install -q -r requirements.txt && pip install -q -r requirements-optional.txt && python setup.py install && cd ../
  # pymatgen master
  #- git clone https://github.com/materialsproject/pymatgen.git && cd pymatgen && pip install -q -r requirements.txt && pip install -q -r requirements-optional.txt && python setup.py install && cd ../

  #- git clone --depth=50 https://github.com/gmatteo/pymatgen.git && cd pymatgen && python setup.py install && cd ../
  #- git clone --depth=50 https://github.com/abinit/abipy.git && cd abipy && python setup.py install && cd ../

  - python setup.py install
  - mkdir -p ${HOME}/.abinit/abipy 
  - cp dev_scripts/travis_scheduler.yml ${HOME}/.abinit/abipy/scheduler.yml
  - cp dev_scripts/travis_manager.yml ${HOME}/.abinit/abipy/manager.yml
    #- ./dev_scripts/pyclean.py .

# command to run tests
script: ./dev_scripts/runtests.sh

branches:
  only:
    - master

after_success:
    - if [[ "${ABIPY_COVERALLS}" == "yes" ]]; then coveralls; fi

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
