language: python
cache: pip

#dist: precise
sudo: false

env:
  global:
    - ABINIT_VERSION=8.10.1
    - ABIPY_PYTEST=yes
    - OPENBLAS_NUM_THREADS=1
    - OMP_NUM_THREADS=1

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - ABIPY_INSTALLER=pip ABIPY_COVERALLS=yes
    - os: linux
      python: 3.7
      env:
        - ABIPY_INSTALLER=conda

install:
  #- set -ev  # exit on first error, print each command
  - env
  - ulimit -s unlimited

  - |
      if [ "${ABIPY_INSTALLER}" == "pip" ]; then
        # pip-based installation.
        source dev_scripts/conda_get.sh  # Needed for Abinit
        travis_wait pip install -r requirements.txt
        travis_wait pip install -r requirements-optional.txt

      elif [ "${ABIPY_INSTALLER}" == "conda" ]; then
        # Install conda https://conda.io/docs/travis.html
        source dev_scripts/conda_get.sh
        source dev_scripts/conda_install.sh
      fi

  - python setup.py install
  - mkdir -p ${HOME}/.abinit/abipy
  - cp dev_scripts/travis_scheduler.yml ${HOME}/.abinit/abipy/scheduler.yml
  - cp dev_scripts/travis_manager.yml ${HOME}/.abinit/abipy/manager.yml
  - ./dev_scripts/pyclean.py .

# command to run tests
script: ./dev_scripts/runtests.sh

branches:
  only:
    - master

after_success:
    - if [[ "${ABIPY_COVERALLS}" == "yes" ]]; then coveralls; fi

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
