language: python
python:
  - "2.7"
#before_install:
#
# command to install dependencies
#install: "pip install -r requirements.txt --use-mirrors"
#install: "pip install"
# This is needed, otherwise, nosetests will import try to import wx.
#before_script:
    #- rm abipy/gui/__init__.py 
    #- export LD_LIBRARY_PATH=/usr/lib/:$LD_LIBRARY_PATH
    #- python -m netCDF4_utils
    #- abipy/dev_scripts/check_netcdf4.py

# Setup anaconda to facilitate the installation of numpy and scipy
# See https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  # Coverage packages are on my binstar channel
  #- conda install --yes -c dan_blanchard python-coveralls nose-cov
  - python setup.py install
# command to run tests
 script: nosetests
 branches:
   only:
     - foobar
 notifications:
   email:
     recipients:
       - gmatteo@gmail.com
     on_success: change
     on_failure: always
# Calculate coverage
# after_success:
#   - coveralls --config_file .coveragerc
#
